[tool.poetry]
name = "blagues_api"
version = "1.0.4"
description = "Official client for Blagues API"
homepage = "https://www.blagues-api.fr/"
authors = [
  "baptiste0928 <contact@baptiste0928.net>",
  "DraftMan <contact@draftman.fr>",
  "Awakno <awaknocode@gmail.com>"
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Blagues-API/package-py"

[tool.poetry.dependencies]
python = "^3.14.4"
aiohttp = "^3.13.5"
pydantic = "^2.13.2"

[tool.poetry.dev-dependencies]
pytest = "^9.0.3"
pytest-asyncio = "^1.3.0"
python-dotenv = "^1.2.2"
flake8 = "^7.3.0"
flake8-pyproject = "^1.2.4"
black = "^26.3.1"
isort = "^8.0.1"
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.flake8]
max-line-length = 120
exclude = [".venv"]

[tool.isort]
profile = "black"
